version: '3'

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
    image: ameba_bot_telegram
    env_file:
      - .env
